name: Project-Stats CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *' # every 4 hours
  repository_dispatch:
    types: [sync-project-data]

env:
  THIRD_PARTY_GIT_AUTHOR_EMAIL: opensource+bot@newrelic.com
  THIRD_PARTY_GIT_AUTHOR_NAME: nr-opensource-bot

jobs:
  job-sync-project-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: liz/project-stats
          fetch-depth: 0
          token: ${{ secrets.DEVEX_OPENSOURCE_BOT_TOKEN }}

      - name: Install dependencies
        run: cd .github/actions/sync-data && npm install

      - name: Sync Data
        uses: ./.github/actions/sync-data
        with:
          # runs queries against GitHub API; must have push access to repos for stats queries to work
          # this token is _only_ used for this GH action
          github-token: ${{ secrets.OPENSOURCE_STATS_TOKEN }}
          project-stats: true

      - name: Commit data files
        run: |
          echo "success"
