name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - 'liz/project-stats-bug'

env:
  THIRD_PARTY_GIT_AUTHOR_EMAIL: opensource+bot@newrelic.com
  THIRD_PARTY_GIT_AUTHOR_NAME: nr-opensource-bot

jobs:
  job-sync-project-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.DEVEX_OPENSOURCE_BOT_TOKEN }}

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: cd .github/actions/test-action && npm install

      - name: Sync Data
        uses: ./.github/actions/test-action
        with:
          # runs queries against GitHub API; must have push access to repos for stats queries to work
          # this token is _only_ used for this GH action
          github-token: ${{ secrets.OPENSOURCE_STATS_TOKEN }}
          project-stats: true

      - name: Commit data files
        run: |
          echo "Updated project data files"
